export const ApiErrorCodes = {
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
    BAD_REQUEST: 'BAD_REQUEST',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    CONFLICT: 'CONFLICT',
    DATABASE_ERROR: 'DATABASE_ERROR',
    SERVICE_ERROR: 'SERVICE_ERROR',
    SYSTEM_CUOTA_ERROR: 'SYSTEM_CUOTA_ERROR',
  }